apiVersion: v1
kind: Service
metadata:
  name: literature-frontend-svc
  namespace: literature
  labels:
    app: literature-frontend
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30225
  selector:
    app: literature-frontend